//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autorepair.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirment
    {
        public int RequirmentsID { get; set; }
        public string RequirmentsFirstName { get; set; }
        public string RequirmentsLastName { get; set; }
        public string RequirmentsEmail { get; set; }
        public string RequirmentsBrand { get; set; }
        public Nullable<System.DateTime> RequirmentsYearOfMade { get; set; }
        public Nullable<double> RequirmentsEngineCapacity { get; set; }
        public string RequirmentsTypeOfEngine { get; set; }
        public string RequirmentsDescriptionOfProblem { get; set; }
        public string RequirmentsStatus { get; set; }
    }
}
