//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC_HomeWork12_server.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WritableRow
    {
        public System.Guid WritableRowID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Text { get; set; }
        public string Nickname { get; set; }
    }
}
