//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC_HomeWork11_client.ServiceHomeWork {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDO", Namespace="http://schemas.datacontract.org/2004/07/JC_HomeWork11.DataObjects")]
    [System.SerializableAttribute()]
    public partial class OrderDO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> orderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.customerIDField, value) != true)) {
                    this.customerIDField = value;
                    this.RaisePropertyChanged("customerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> orderDate {
            get {
                return this.orderDateField;
            }
            set {
                if ((this.orderDateField.Equals(value) != true)) {
                    this.orderDateField = value;
                    this.RaisePropertyChanged("orderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderID {
            get {
                return this.orderIDField;
            }
            set {
                if ((this.orderIDField.Equals(value) != true)) {
                    this.orderIDField = value;
                    this.RaisePropertyChanged("orderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceHomeWork.IServiceHomeWork")]
    public interface IServiceHomeWork {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHomeWork/GetOrders", ReplyAction="http://tempuri.org/IServiceHomeWork/GetOrdersResponse")]
        JC_HomeWork11_client.ServiceHomeWork.OrderDO[] GetOrders(string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHomeWork/GetOrders", ReplyAction="http://tempuri.org/IServiceHomeWork/GetOrdersResponse")]
        System.Threading.Tasks.Task<JC_HomeWork11_client.ServiceHomeWork.OrderDO[]> GetOrdersAsync(string customerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHomeWorkChannel : JC_HomeWork11_client.ServiceHomeWork.IServiceHomeWork, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHomeWorkClient : System.ServiceModel.ClientBase<JC_HomeWork11_client.ServiceHomeWork.IServiceHomeWork>, JC_HomeWork11_client.ServiceHomeWork.IServiceHomeWork {
        
        public ServiceHomeWorkClient() {
        }
        
        public ServiceHomeWorkClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHomeWorkClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHomeWorkClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHomeWorkClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JC_HomeWork11_client.ServiceHomeWork.OrderDO[] GetOrders(string customerID) {
            return base.Channel.GetOrders(customerID);
        }
        
        public System.Threading.Tasks.Task<JC_HomeWork11_client.ServiceHomeWork.OrderDO[]> GetOrdersAsync(string customerID) {
            return base.Channel.GetOrdersAsync(customerID);
        }
    }
}
